@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjEwMjE2NTd9.hMpPit2Wn4Q0rdHg3Lc1LHmuIq6bt_AGpwBUpnUX3GY

# Users

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "dude",
  "email": "dude@example.com",
  "password": "password",
  "password_confirmation": "password"
}



# Sessions

### Sessions Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "dude@example.com",
  "password": "password"
}



# Products

### Products Index
GET http://localhost:3000/products.json

### Products Show
GET http://localhost:3000/products/1.json



# Orders

### Orders Index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### Orders Show
GET http://localhost:3000/orders/6.json
Authorization: Bearer {{jwt}}

### Orders Create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
	"product_id": 4,
	"quantity": 5
}