Photo.create(name: "Shell", description: "image of a shell at Red Bank Battlefield Park, New Jersey")
Photo.create(name: "Paint Square", description: "paint square found on a tree at Sourland Mountain Park")
Photo.create(name: "Desert Landscape", description: "desert landscape, somewhere in the American Southwest")
Photo.create(name: "Sunset Glass", description: "sunset seen through a piece of broken glass at Valley Forge")
Photo.create(name: "Canyon Sunset", description: "sunset over the Grand Canyon")
Photo.create(name: "Snail", description: "snail at Brandywine Creek State Park, Delaware")
Photo.create(name: "Flower", description: "flower in Germantown")
Photo.create(name: "Bee", description: "bee pollinating a marigold")
Photo.create(name: "Bolts", description: "piece of construction at Red Bank Battlefield Park")
Photo.create(name: "Rock Wall", description: "rock wall at the Grand Canyon")
Image.create(photo_id: 1, name: "Shell", description: "shell full", url: "https://live.staticflickr.com/65535/52297242829_5c9ead51da_k.jpg")
Image.create(photo_id: 2, name: "Paint Square", description: "paint square full", url: "https://live.staticflickr.com/65535/52295993622_b5cab4f219_k.jpg")
Image.create(photo_id: 3, name: "Desert Landscape", description: "desert landscape full", url: "https://live.staticflickr.com/65535/52297242764_378eaaab1d_k.jpg")
Image.create(photo_id: 4, name: "Sunset Glass", description: "sunset glass full", url: "https://live.staticflickr.com/65535/52296977491_21ee214562_k.jpg")
Image.create(photo_id: 5, name: "Canyon Sunset", description: "canyon sunset full", url: "https://live.staticflickr.com/65535/52295993682_34a3152559_k.jpg")
Image.create(photo_id: 6, name: "Snail", description: "snail full", url: "https://live.staticflickr.com/65535/52297470625_f185f86d43_k.jpg")
Image.create(photo_id: 7, name: "Flower", description: "flower full", url: "https://live.staticflickr.com/65535/52297242709_717db6bd52_k.jpg")
Image.create(photo_id: 8, name: "Bee", description: "bee full", url: "https://live.staticflickr.com/65535/52297470500_e9ad8b0815_k.jpg")
Image.create(photo_id: 9, name: "Bolts", description: "bolts full", url: "https://live.staticflickr.com/65535/52297470600_5e06600988_k.jpg")
Image.create(photo_id: 10, name: "Rock Wall", description: "rock wall full", url: "https://live.staticflickr.com/65535/52297242789_c148ad0a04_k.jpg")
Image.create(photo_id: 1, name: "Shell zoom", description: "crop of Shell showing detail")
Product.create(name: "Large Matte Print", description: "large print of a photograph", size: "24in x 36in", print_type: "matte", price: 14.95)
Product.create(name: "Large Gloss Print", description: "large print of a photograph", size: "24in x 36in", print_type: "gloss", price: 14.95)
Product.create(name: "Small Matte Print", description: "small print of a photograph", size: "8in x 12in", print_type: "matte", price: 9.95)
Product.create(name: "Small Gloss Print", description: "small print of a photograph", size: "8in x 12in", print_type: "gloss", price: 9.95)
Product.create(name: "Mug", description: "12oz mug with printed photograph (for Amanda)", size: "12oz", print_type: "screen", price: 12.95)