Product.create(name: "Shell", description: "shell", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "Paint Square", description: "paint square", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "Desert Landscape", description: "desert landscape", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "Sunset Glass", description: "sunset glass", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "Canyon Sunset", description: "canyon sunset", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "Snail", description: "snail", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "Flower", description: "flower", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "Bee", description: "bee", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "Bolts", description: "bolts", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "Rock Wall", description: "rock wall", price: 0, size: "demo size", print_type: "digital")
Image.create(product_id: 1, name: "Shell", description: "image of shell", url: "https://live.staticflickr.com/65535/52297242829_5c9ead51da_k.jpg")
Image.create(product_id: 2, name: "Paint Square", description: "paint square", url: "https://live.staticflickr.com/65535/52295993622_b5cab4f219_k.jpg")
Image.create(product_id: 3, name: "Desert Landscape", description: "desert landscape", url: "https://live.staticflickr.com/65535/52297242764_378eaaab1d_k.jpg")
Image.create(product_id: 4, name: "Sunset Glass", description: "sunset glass", url: "https://live.staticflickr.com/65535/52296977491_21ee214562_k.jpg")
Image.create(product_id: 5, name: "Canyon Sunset", description: "canyon sunset", url: "https://live.staticflickr.com/65535/52295993682_34a3152559_k.jpg")
Image.create(product_id: 6, name: "Snail", description: "snail", url: "https://live.staticflickr.com/65535/52297470625_f185f86d43_k.jpg")
Image.create(product_id: 7, name: "Flower", description: "flower", url: "https://live.staticflickr.com/65535/52297242709_717db6bd52_k.jpg")
Image.create(product_id: 8, name: "Bee", description: "bee", url: "https://live.staticflickr.com/65535/52297470500_e9ad8b0815_k.jpg")
Image.create(product_id: 9, name: "Bolts", description: "bolts", url: "https://live.staticflickr.com/65535/52297470600_5e06600988_k.jpg")
Image.create(product_id: 10, name: "Rock Wall", description: "rock wall", url: "https://live.staticflickr.com/65535/52297242789_c148ad0a04_k.jpg")
