Product.create(name: "shell", description: "shell", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "paint square", description: "paint square", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "desert landscape", description: "desert landscape", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "sunset glass", description: "sunset glass", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "canyon sunset", description: "canyon sunset", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "snail", description: "snail", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "flower", description: "flower", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "bee", description: "bee", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "bolts", description: "bolts", price: 0, size: "demo size", print_type: "digital")
Product.create(name: "rock wall", description: "rock wall", price: 0, size: "demo size", print_type: "digital")
Image.create(product_id: 1, name: "shell", description: "shell", url: "https://drive.google.com/file/d/14HDJNP3GKCalsH1D-_-se2-ezUJpRMDF/view?usp=sharing")
Image.create(product_id: 2, name: "paint square", description: "paint square", url: "https://drive.google.com/file/d/15PMST3exgGaRCPXN5gasqFAahREJghiD/view?usp=sharing")
Image.create(product_id: 3, name: "desert landscape", description: "desert landscape", url: "https://drive.google.com/file/d/1JyXf3UvSDm0UCTWS1nrjAiRVQucAzi2H/view?usp=sharing")
Image.create(product_id: 4, name: "sunset glass", description: "sunset glass", url: "https://drive.google.com/file/d/1MPu-_-A1dG8o406JjjGg5b24hVhXBTyY/view?usp=sharing")
Image.create(product_id: 5, name: "canyon sunset", description: "canyon sunset", url: "https://drive.google.com/file/d/1NBDCOnc5WpFEyYp84xxuiGxuPKbXvdme/view?usp=sharing")
Image.create(product_id: 6, name: "snail", description: "snail", url: "https://drive.google.com/file/d/1gvLZSxLWa7Bc7-lwzMoJCzqHxmBavG3x/view?usp=sharing")
Image.create(product_id: 7, name: "flower", description: "flower", url: "https://drive.google.com/file/d/1hNvLTm84SmRQRg7_KkbpyowWduNCEeBZ/view?usp=sharing")
Image.create(product_id: 8, name: "bee", description: "bee", url: "https://drive.google.com/file/d/1kr4XZBQDx36E2gmlJYgiacKBZpKNF7lz/view?usp=sharing")
Image.create(product_id: 9, name: "bolts", description: "bolts", url: "https://drive.google.com/file/d/1rS8U9ClxjO5fkLe8E_5WJOpMM-ua7CXC/view?usp=sharing")
Image.create(product_id: 10, name: "rock wall", description: "rock wall", url: "https://drive.google.com/file/d/1tIjYudtOLhPAaNm31UpWw6hkZRuED_pT/view?usp=sharing")